version: '3.8'

services:
  dev-db:
    container_name: auth_project_dev_db
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - backend-nestjs
  test-db:
    container_name: auth_project_test_db
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - backend-nestjs
networks:
  backend-nestjs:
